copy ichigo-audio\Debug\*.dll output
copy ichigo-audio\Debug\*.exp output
copy ichigo-audio\Debug\*.pdb output
copy dependencies\win32\bass\*.dll output
copy dependencies\win32\bass_aac\*.dll output
copy dependencies\win32\bass_alac\*.dll output
copy dependencies\win32\bass_ape\*.dll output
copy dependencies\win32\bass_fx\*.dll output
copy dependencies\win32\bass_mpc\*.dll output
copy dependencies\win32\bassflac\*.dll output
copy dependencies\win32\basswv\*.dll output
copy dependencies\win32\tags\*.dll output